PreOnBoarding-Team-16/1stweek-sirloin-task

.gitignore
=> Add : .gitignore 파일에 vscode 추가

src/Component/Container/index.js
공용 컴포넌트가 될 Container의 형태를 정의했습니다!
=> Modfy Continer/index.js

package-lock.json, package.json, src/App.js, src/Style/GlobalStyle.js, src/index.js
=> Add : Style폴더 GlobalStyle.js 추가

src/Component/Container/index.js
props 인용방식을 수정했습니다! JSX를 그대로 사용하는건 오류가 나네요.
=> Modify Container/index.js

src/Style/GlobalStyle.js, src/Style/index.js, src/index.js
=> Modify: GloblaStyle import 방식 수정

src/Component/Container/index.js, src/Component/Nav/Nav.js, src/Style/index.js, src/index.js
=> Modify: GlobalStyle 경로 수정

public/index.html, src/App.js, src/Component/Nav/Nav.js, src/index.js
=> Modify: GlobalStyle 선언 위치 변경

package-lock.json, package.json, src/Util/SelectImg/index.js, src/Util/SelectImg/style.js
이미지를 입력할 수 있는 버튼이 담긴 컴포넌트입니다.
props로 이미지를 저장할 배열, 배열의 setter func을 받습니다.
=> ADD: SelectImg

package-lock.json, package.json, src/App.js, src/Component/Nav/Nav.js, src/Style/GlobalStyle.js, src/Style/index.js
=> Add : Nav 레이아웃 추가

src/Component/ProductInfo/index.js, src/Component/ProductInfo/style.js
레이아웃(static version) 작업 진행중입니다.
=> Modifiy: 스타일 컴포넌트 분리,레이아웃 설계

src/Component/ProductInfo/index.js, src/Component/ProductInfo/style.js
=> Modifiy: 반복 요소 코드 리팩토링

package-lock.json, package.json, src/App.js, src/Component/Nav/Nav.js, src/Component/Nav/NavStyle.js
=> Add : Nav 완성

src/Component/Container/index.js, src/Component/Container/style.js, src/Component/MDOption/index.js, src/Component/MDOption/style.js, src/Component/Nav/Nav.js, src/Component/Nav/NavStyle.js, src/Component/ProductInfo/style.js, src/Component/ProductSalesperiod/index.js, src/Style/GlobalStyle.js, src/Util/SelectImg/index.js, src/Util/SelectImg/style.js
Nav 에러 수정 & GlobalStyle 바탕색 적용
=> Modify: Nav 에러 수정 & GlobalStyle 바탕색 적용

src/Component/ProductInfo/index.js, src/Component/ProductInfo/style.js
=> Modifiy: 반복 요소 코드 리펙토링, 컴포넌트 구조 변경

src/App.js, src/Component/ProductInfo/style.js, src/store/PIData.js
ProductInfo Component를 위한 전역 state 등록
=> Add: ProductInfo 전역 state 등록

src/Component/PDoption/index.js, src/Component/PDoption/style.js
Optionset component를 삭제가능한 버튼 구현
=> Add Pdoption

src/Component/ProductInfo/index.js, src/store/PDdata.js
=> Modify: store/PDdata.PIData 초기 데이터 설정

src/Component/ProductInfo/index.js, src/store/PDdata.js
=> Add: ProductInfo state 관리 로직 설계

src/Component/ProductInfo/index.js, src/Component/ProductInfo/style.js
Category 추가/삭제 완료 
FilterTag 추가 완료
FitlerTag 삭제 작업중
=> Add: Category 추가/삭제 기능 완료

src/Component/ProductInfo/index.js
=> Add: FilterTag 추가/삭제 기능 구현

src/Component/ProductInfo/index.js, src/store/PDdata.js
=> Add: FilterTag 검색 기능 구현

src/Component/ProductInfo/index.js
처음 로드때 데이터가 sort가 안되어 있어서 메소드를 만들어서 해결하였습니다
=> Fix: 처음 데이터 로드부터 정렬되도록 수정

src/Component/PDoption/index.js, src/Component/PDoption/style.js
=> PDOption 완료입니다!

src/Component/ProductInfo/index.js
Util을 활용하여 Thumbnail 설정 기능을 구현하였습니다.
=> Add: Thumbnail 설정 기능 구현

src/Component/ProductInfo/index.js, src/store/PDdata.js
=> Add: ProductInfo 대표 이미지 삭제 기능, 상품 고유 번호 생성 함수 추가

src/Component/ProductInfo/index.js, src/Component/ProductSalesperiod/PScontentBox.js, src/Util/DateTime/Date.js, src/Util/DateTime/index.js
Modify: Util/DateTime 공통 컴포넌트 완성
=> Modify: Util/DateTime 공통 컴포넌트 완성

src/App.js, src/Component/ProductInfo/style.js
=> Style App.js

src/App.js
=> Modify App.js

src/App.js, src/Component/ProductDelivery/index.js, src/Component/ProductDelivery/style.js, src/Component/ProductInfoNotice/ProductInfo.js, src/Component/ProductInfoNotice/index.js, src/Component/ProductInfoNotice/style.js, src/store/PDdata.js
PDdata에 초기데이터를 설정하고 ProductInfoNotice 컴포넌트를 구현하였습니다.
=> ProductInfoNotice 컴포넌트 구현

src/App.js, src/Component/PDMileage/index.js, src/Component/PDMileage/style.js, src/Util/Toggle/index.js, src/store/PDdata.js
=> Toggle Comp 업데이트

package.json
=> Modify: package.json 파일 ; 삭제

src/Component/ProductSalesperiod/PScontentBoxSecond.js, src/Component/ProductSalesperiod/index.js, src/Component/ProductSalesperiod/style.js
Modify: ProductSalesperiod 폴더 radio 버튼 수정중
=> Modify: ProductSalesperiod 폴더 radio 버튼 수정중

src/Component/ProductSalesperiod/PScontentBox.js, src/Component/ProductSalesperiod/PScontentBoxSecond.js, src/store/PDdata.js
Modify: ProductSaleSperiod 상태값 전역에 저장
=> Modify: ProductSaleSperiod 상태값 전역에 저장

src/Component/PDoption/index.js
옵션 세트를 삭제할때, 다시 동적으로 생성되는 option들이 optionvalue가 초기화되는 부분을 수정했습니다!
=> Modify PDoption.js

src/Component/ProductDelivery/index.js, src/store/PDdata.js
=> style: 초기 데이터 분리

src/App.js, src/Component/ProductInfoNotice/style.js, src/Util/DateTimePicker/index.js
급하게 가져온거라 테스트 몇가지 뺴먹은 부분이 있을꺼같아요.
이슈있을시 바로 연락주세요
=> 새로운 MUI component를 가져왔습니다.

src/Component/ProductSalesperiod/PScontentBox.js, src/Component/ProductSalesperiod/index.js, src/Util/RadioButton/index.js
=>  "Add: 추가"
